swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transactions Module
      summary: Get All Transactions
      description: Retrieve all transactions for the current month
      parameters:
        - in: query
          name: month
          description: Filter transactions by month
          required: false
          type: string
          format: date
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved transactions
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '500':
          description: Internal Server Error
    post:
      tags:
        - Transactions Module
      summary: Create Transaction
      description: Create a new transaction
      parameters:
        - in: body
          name: body
          description: Transaction data
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction created successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Get Transaction Details
      description: Retrieve details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved transaction details
          schema:
            $ref: '#/definitions/TransactionResponse'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions Module
      summary: Update Transaction
      description: Update details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Updated transaction data
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Transactions Module
      summary: Delete Transaction
      description: Delete a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to delete
          required: true
          type: string
      produces:
        - application/json
      responses:
        '204':
          description: Transaction deleted successfully
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
definitions:
  Transaction:
    properties:
      amount:
        type: number
        description: Transaction amount
      description:
        type: string
        description: Transaction description
  TransactionResponse:
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      amount:
        type: number
        description: Transaction amount
      description:
        type: string
        description: Transaction description
  TransactionsResponse:
    type: array
    items:
      $ref: '#/definitions/TransactionResponse'
